import os
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

ROOT_DIR = Path(
    os.getenv(
        "ROOT_DIR",
        Path(os.path.dirname(os.path.abspath(__file__))) / "..",
    )
)

# ── Paths ──────────────────────────────────────────────────────────────────
DIR2DATA = ROOT_DIR / "data"
DIR2COHORT = DIR2DATA / "cohort"
DIR2EXPERIENCES = DIR2DATA / "experiences"
DIR2RESULTS = DIR2DATA / "results"

# MIMIC-IV raw CSV.GZ files (downloaded from PhysioNet)
DIR2MIMIC = Path(os.getenv("DIR2MIMIC", ROOT_DIR / "mimic-iv"))

# Derived concept tables (parquet, generated by data/build_derived.py via DuckDB + mimic-code)
DIR2DERIVED = Path(os.getenv("DIR2DERIVED", DIR2DATA / "derived"))

# Raw MIMIC tables exported to parquet (generated by data/build_derived.py)
DIR2RAW = Path(os.getenv("DIR2RAW", DIR2DATA / "raw"))

# ── Column names (shared with caumim) ─────────────────────────────────────
COLNAME_PATIENT_ID = "subject_id"
COLNAME_HADM_ID = "hadm_id"
COLNAME_ICUSTAY_ID = "stay_id"
COLNAME_CODE = "code"
COLNAME_LABEL = "label"
COLNAME_VALUE = "value"
COLNAME_DOMAIN = "domain"
COLNAME_START = "starttime"
COLNAME_END = "endtime"
COLNAMES_EVENTS = [
    COLNAME_PATIENT_ID,
    COLNAME_HADM_ID,
    COLNAME_ICUSTAY_ID,
    COLNAME_START,
    COLNAME_END,
    COLNAME_DOMAIN,
    COLNAME_CODE,
    COLNAME_LABEL,
    COLNAME_VALUE,
]
STAY_KEYS = [COLNAME_PATIENT_ID, COLNAME_ICUSTAY_ID, COLNAME_HADM_ID]

# ── Cohort timestamps ──────────────────────────────────────────────────────
COLNAME_INCLUSION_START = "inclusion_start"      # first broad-spectrum abx
COLNAME_DECISION_TIME = "decision_time"           # time zero = inclusion + 72h
COLNAME_INTERVENTION_STATUS = "treatment_arm"     # 0=continue, 1=deescalate, 2=stop

# ── Treatment arm labels ───────────────────────────────────────────────────
TREATMENT_ARM_CONTINUE = 0
TREATMENT_ARM_DEESCALATE = 1
TREATMENT_ARM_STOP = 2
TREATMENT_ARM_LABELS = {
    TREATMENT_ARM_CONTINUE: "Continue broad-spectrum",
    TREATMENT_ARM_DEESCALATE: "De-escalate",
    TREATMENT_ARM_STOP: "Stop antibiotics",
}

# ── Outcome column names ───────────────────────────────────────────────────
COLNAME_VFD28 = "ventilator_free_days_28"         # days alive & off ventilator
COLNAME_VAPFD28 = "vasopressor_free_days_28"       # days alive & off vasopressors
COLNAME_ICU_LOS = "icu_los_days"                  # days alive & in ICU (censored)
COLNAME_AKI_WORSENING = "aki_worsening"           # KDIGO stage increase after T0
COLNAME_SECONDARY_INFECTION = "secondary_infection"  # new +ve culture after day 7
COLNAME_CDIFF_28D = "cdiff_28d"                   # F20: new oral vanco/metronidazole order
COLNAME_MORTALITY_28D = "mortality_28days"
COLNAME_MORTALITY_90D = "mortality_90days"
# WS11: multi-horizon trajectory of mortality
COLNAME_MORTALITY_7D = "mortality_7d"
COLNAME_MORTALITY_14D = "mortality_14d"
COLNAME_MORTALITY_21D = "mortality_21d"

ALL_OUTCOMES = [
    COLNAME_VFD28,
    COLNAME_VAPFD28,
    COLNAME_ICU_LOS,
    COLNAME_AKI_WORSENING,
    COLNAME_SECONDARY_INFECTION,
    COLNAME_CDIFF_28D,
    COLNAME_MORTALITY_7D,
    COLNAME_MORTALITY_14D,
    COLNAME_MORTALITY_21D,
    COLNAME_MORTALITY_28D,
]
# Ordered sequence used for trajectory plotting and joint-bootstrap CIs.
MORTALITY_TRAJECTORY = [
    (7,  COLNAME_MORTALITY_7D),
    (14, COLNAME_MORTALITY_14D),
    (21, COLNAME_MORTALITY_21D),
    (28, COLNAME_MORTALITY_28D),
]

# ── Confounder feature groups ──────────────────────────────────────────────
FEATURES_SEVERITY = [
    "SOFA_at_decision",
    "SAPSII",
    "lactate_at_decision",
    "vasopressors_at_decision",
    "MAP_at_decision",
]
FEATURES_INFECTION = [
    "CRP_at_decision",       # C-reactive protein (PCT not consistently coded in MIMIC-IV)
    "WBC_at_decision",       # white blood cell count
    "temperature_at_decision",
    "positive_blood_culture",
    "culture_gram_positive",
    "culture_gram_negative",
    "infection_source_pulmonary",
    "infection_source_urinary",
    "infection_source_abdominal",
]
FEATURES_ORGAN = [
    "AKI_stage_at_decision",
    "pf_ratio_at_decision",  # PaO2 / FiO2
    "ventilation_at_decision",
    "creatinine_at_decision",
    "bilirubin_at_decision",
]
FEATURES_TREATMENT_HISTORY = [
    "days_on_abx",           # days from inclusion to decision
    "prior_carbapenem",
    "prior_glycopeptide",
    "prior_betalactam",
    "prior_aminoglycoside",
]
FEATURES_TRAJECTORY = [
    "delta_SOFA_0_72h",      # SOFA at 72h minus SOFA at 0h (improvement < 0)
    "delta_WBC_0_72h",
    "delta_lactate_0_72h",
    "delta_temperature_0_72h",
    "delta_creatinine_0_72h",
]
FEATURES_DEMOGRAPHICS = [
    "admission_age",
    "Female",
    "immunosuppressed",
    "charlson_comorbidity_index",
    "emergency_admission",
]
# WS4: Clinical-intent proxies (reviewer concern #1/#2).
# Code status is emitted as one-hot binary columns by the extractor; the CMO
# category is excluded from the cohort upstream.
FEATURES_CLINICAL_INTENT = [
    "code_status_full_code",
    "code_status_dnr",
    "code_status_dni",
    "code_status_dnr_dni",
    "code_status_unknown",
    "palliative_transition_pre_T0",
    "id_consult_pre_T0",
    "source_control_pre_T0",
]

FEATURE_SETS = {
    "All confounders": (
        FEATURES_SEVERITY
        + FEATURES_INFECTION
        + FEATURES_ORGAN
        + FEATURES_TREATMENT_HISTORY
        + FEATURES_TRAJECTORY
        + FEATURES_DEMOGRAPHICS
        + FEATURES_CLINICAL_INTENT
    ),
    "Without infection markers": (
        FEATURES_SEVERITY
        + FEATURES_ORGAN
        + FEATURES_TREATMENT_HISTORY
        + FEATURES_TRAJECTORY
        + FEATURES_DEMOGRAPHICS
        + FEATURES_CLINICAL_INTENT
    ),
    "Without trajectory": (
        FEATURES_SEVERITY
        + FEATURES_INFECTION
        + FEATURES_ORGAN
        + FEATURES_TREATMENT_HISTORY
        + FEATURES_DEMOGRAPHICS
        + FEATURES_CLINICAL_INTENT
    ),
    "Severity + demographics": FEATURES_SEVERITY + FEATURES_DEMOGRAPHICS,
    # WS4: ablation to quantify the marginal contribution of intent proxies.
    "Without clinical intent": (
        FEATURES_SEVERITY
        + FEATURES_INFECTION
        + FEATURES_ORGAN
        + FEATURES_TREATMENT_HISTORY
        + FEATURES_TRAJECTORY
        + FEATURES_DEMOGRAPHICS
    ),
}

# ── CATE heterogeneity features ────────────────────────────────────────────
CATE_FEATURES = [
    "admission_age",
    "Female",
    "SOFA_at_decision",
    "positive_blood_culture",
    "immunosuppressed",
    "delta_SOFA_0_72h",
]

# ── Experiment constants ───────────────────────────────────────────────────
RANDOM_STATE = 42
# Propensity-score clipping floor (and 1-MIN_PS_SCORE ceiling).
# 0.001 lets a near-zero-propensity row dominate the estimator with weight ~1000.
# 0.05 is the convention in observational pharmaco-epi (Stürmer 2010; Crump 2009).
MIN_PS_SCORE = 0.05
# Outcomes that should be modeled as binary (model_y uses a classifier).
BINARY_OUTCOMES = {
    "mortality_28days",
    "mortality_90days",
    "mortality_7d",     # WS11
    "mortality_14d",    # WS11
    "mortality_21d",    # WS11
    "aki_worsening",
    "secondary_infection",
    "cdiff_28d",
}

# ── Result column names ────────────────────────────────────────────────────
RESULT_ATE = "ATE"
RESULT_ATE_LB = "ATE lower bound"
RESULT_ATE_UB = "ATE upper bound"
RESULT_TREATMENT_COMPARISON = "treatment_comparison"

FILENAME_TARGET_POPULATION = "target_population.parquet"
FILENAME_INCLUSION_CRITERIA = "inclusion_criteria.pkl"
